Izzy/hashtable
terralang/std pull request #16
Opened 2021-06-30 03:51 UTC by ILikePizza555

Basic dense_hash_table implementation.

Things left to do:

- [ ] Entry API
- [ ] Adding more basic functions
- [ ] Default hash function needs to support more types
- [ ] Default equality function needs to support more types
- [ ] Make this into a *HashMap* (store keys along with values)

2021-06-30 04:01 UTC, ErikMcClure requested changes
Looks good aside from some minor fixes, and obviously the missing features already outlined.

2021-06-30 04:01 UTC, ErikMcClure commented on hashtable.t
> +	else
The default case should only actually work on primitive types, fixed-size arrays, and vectors. If it's not a primitive type, default to trying to call a "hash" function from the type, or if it doesn't exist, throw an error.

2021-06-30 04:01 UTC, ErikMcClure commented on hashtable.t
> +	-- TODO: Need more cases here too
This function currently doesn't actually work with strings, remember to add that in and also add tests for strings specifically.

2021-10-05 22:26 UTC, aiverson requested changes

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		CStr.memset(metadata_array, SM.MetadataEmpty, capacity)
Use the feature from alloc instead of using the one grabbed from a C header. The stdlib should minimize the usage of C headers and aggregate any requires of C header inclusion to single places if possible.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	local MetadataHashBitmap = constant(uint8, 127) -- 0b01111111
rename s/Bitmap/Bitmask/

2021-10-05 22:26 UTC, aiverson commented on .gitignore
> +std
Why was this added? this seems counterproductive.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		return "[" .. tostring(KeyType) .. (BucketType.IsKeyValue and (", " .. tostring(ValueType)) or "") .. "]"
Square bracket syntax seems inappropriate for the usages of this function. Why was this chosen over parentheses?

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +terra M.hash_djb2(data: &int8, size: uint): uint
This is the wrong type. The size should be of type intptr, otherwise computing the hash of valid, if unusually large, single objects will fail. The result of the hash should be a uint64 rather than a uint32, which decreases the probability of collision without decreasing the performance on modern 64 bit machines (note: benchmark to verify that. vectorization might be affected). Additionally, the setup as a raw pointer makes it inconvenient, inefficient, or impossible to use to construct hash functions of objects which do not use a single contiguous memory buffer, such as Hashed Array Trees, sorted tree sets of hashable objects, linked lists, etc.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	elseif KeyType:isstruct() and KeyType.methods.hash ~= nil then
The comparison with nil is unneeded here. The truthiness of the value directly is adequate.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +			return M.hash_djb2(str, CStr.strlen(str))
This is traversing the string twice, but shouldn't need to.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		if #hash_fn_type.parameters >= 1 then
This check is incorrect, triggering an error if it takes one or more parameters. This will only accept a hash function with no parameters, which is not correct and will trigger a type error a few lines down. This should have been caught by a unit test.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		local terra call_object_hash()
This function does not have a parameter to accept the object it is supposed to be hashing. This won't compile if any struct is ever used as a key in a hashtable.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +M.Errors = {
I think this should be an enum. Why is it set up as a table of constants?

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	-- Result types
These types names don't communicate their jobs well, and also these shouldn't be given names and instead just mentioned at point of use.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		return CallocResult.ok{opaque_ptr, metadata_array, buckets_array}
Returning all three of these things seems redundant

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		return metadata ~= MetadataEmpty and metadata ~= MetadataDeleted
This is implementable with a single bit shift and test, which should be faster. This might optimize to that if the compiler were smart enough, but probably not. This should be tested.

It also might not matter because this could be replaced during the vectorization of the block checks.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	local terra find_next_power_of_two(m: uint): uint
This should probably use the intptr family for an integer of the same size as a pointer.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	local terra linear_probe(hash: HashInformation, metadata_array: &uint8, buckets_array: &BucketType, capacity: uint): ProbeResult
This could probably be condensed and simplified a little, but the way it is set up and commented conveys the function and intent of the code very well. I like this. Good job.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	local terra is_at_capacity(capacity: uint, size: uint): bool
If this is the test for if the table needs to be resized, it isn't right and will degrade the performance to quadratic.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		if calloc_result:is_ok() then
Once the match syntax is finished, this should be changed to use it. For now it's just fine. This is more a note to myself.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +			CStr.memset(self, 0, sizeof(HashTable))
This should both be unnecessary and is being done wrong. Please avoid using the C stdlib for features that are provided natively by the terra stdlib. In this case, the allocator api already provides utilities for clearing memory regions. This should be doable by just setting the capacity to zero, or even not doing anything depending on how it is checked, since Terra doesn't automatically try to call destructors on everything when variables go away like C++.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		if result:is_ok() and metadata_holds_hash(self.metadata[result.ok._1]) then
this line isn't very self-explanatory. Could the field maybe be named? or commented here?

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +			CStr.memset(self.buckets + index, 0, sizeof(BucketType))
Please use the terra allocator memory clear.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +			if is_at_capacity(this.capacity, this.size) then
This test degrades performance to quadratic.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +			if insert_data.old_metadata == MetadataEmpty then
What about if it is being inserted in place of a deleted element? Wouldn't that increase the size too?

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	if IsKeyValue then
This section is very clean

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	local struct Entry {
Why not use an enum?

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +		terra Entry:or_insert(value: ValueType): ValueType
What about a way to unconditionally put in a new value so that an entry can be given a default value, and then manipulated knowing that it exists, then written back to the map? It would be nice to have an fmap for this if we had better closures.

2021-10-05 22:26 UTC, aiverson commented on hashtable.t
> +	terra HashTable:debug_metadata_repr()
I'd like a way to get rid of the dependency on stdio at some point in the future.

2021-10-05 22:26 UTC, aiverson commented on result.t
> +	if to.type_parameters[param_name] ~= expected_value then
This should instead assert that the parameter of from can be cast to the parameter of to, that way type promotion in enums can work nicely.

2021-10-05 22:26 UTC, aiverson commented on spec/hashtable_spec.t
> +	end)
Please add a regression test for reinserting a removed entry correctly increasing the size of the hash table.
Please add a test for a key that isn't a string.

2023-10-30 23:57 UTC, closed without merging